# Generated by Django 4.0.5 on 2022-07-01 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_typeuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
