# Generated by Django 4.0.5 on 2022-07-01 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_order_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
